// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Temple_Tour_SignUp.Models;

namespace Temple_Tour_SignUp.Migrations
{
    [DbContext(typeof(SignUpContext))]
    [Migration("20220323163200_Migrationreboot")]
    partial class Migrationreboot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Temple_Tour_SignUp.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Email = "test@test.com",
                            GroupName = "test",
                            GroupSize = 4,
                            Phone = "555-5555",
                            TimeSlotId = 1
                        });
                });

            modelBuilder.Entity("Temple_Tour_SignUp.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Taken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlotResponse");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            Date = "03-20-2022",
                            Taken = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 2,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 3,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 4,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 5,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 6,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 7,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 8,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 9,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 10,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 11,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 12,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 13,
                            Date = "03-20-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 14,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 15,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 16,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 17,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 18,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 19,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 20,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 21,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 22,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 23,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 24,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 25,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 26,
                            Date = "03-21-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 27,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 28,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 29,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 30,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 31,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 32,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 33,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 34,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 35,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 36,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 37,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 38,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 39,
                            Date = "03-22-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 40,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 41,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 42,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 43,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 44,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 45,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 46,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 47,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 48,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 49,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 50,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 51,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 52,
                            Date = "03-23-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 53,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 54,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 55,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 56,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 57,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 58,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 59,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 60,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 61,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 62,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 63,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 64,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 65,
                            Date = "03-24-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 66,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 67,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 68,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 69,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 70,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 71,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 72,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 73,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 74,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 75,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 76,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 77,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 78,
                            Date = "03-25-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 79,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 80,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 81,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 82,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 83,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 84,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 85,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 86,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 87,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 88,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 89,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 90,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 91,
                            Date = "03-26-2022",
                            Taken = false,
                            Time = "8:00 PM"
                        });
                });

            modelBuilder.Entity("Temple_Tour_SignUp.Models.Appointment", b =>
                {
                    b.HasOne("Temple_Tour_SignUp.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
